### PR TITLE
partially fix travis

### PR DESCRIPTION
**Pull request by stevemart**
This is my attempt to try and get travis fixed. I cannot complete it fully because I have no idea where the `params` variable come from in `handleIncomingSMS.py`. This patch includes:

* `chmod 775` the shell files in `tests`
* Modifying the two python files, `handleIncomingSMS.py` and `iotPub.py` to only have syntax errors related to `params`. This made the `test-flake8.sh` almost pass.
* `test-shellcheck.sh` seems to be failing on stuff that is checked in as part of the initial CI patch, so not sure what to do about that.

## TODO

(hopefully by someone not me)

* Make `test-shellcheck.sh` pass
* Make `test-flake8.sh` pass by fixing `handleIncomingSMS.py`.

Related to #12

### CODE REVIEW

**Comment by stevemart** [comment]
@kkbankol-ibm @loafyloaf thanks for the merge, but to be clear this doesn't completely fix things. I don't know how to address the `params` issue here: https://github.com/IBM/serverless-language-translation/blob/master/handleIncomingSMS.py#L35-L48

**Comment by kkbankol-ibm** [comment]
hey @stevemart, just updated those syntax issues for that handleIncomingSMS file

**Comment by loafyloaf** [comment]
@stevemart 'params' come from the definition of the openwhisk action; the readme goes through setting them up.  Having flake8 ignore that error (F821) seems to be heavy handed, but may be the only option.  Running openwhisk actions through flake8 may just be a bad idea

**Comment by stevemart** [comment]
@kkbankol-ibm please use pull requests rather than committing to master, we don't have a fresh CI result this way. Good to see that the bits we need are in the payload. We should probably update the variable name since `dict` is a predefined name in python. 

@loafyloaf I suspect the build is still broken due to the shellchecker. But it fails on scripts we made to run the scripts. We should address that too.

**Comment by stevemart** [comment]
Related commit https://github.com/IBM/serverless-language-translation/commit/138d5e4015898f359f57a951463f1df34d97cfdf

**Pull request merged**
